In [4]:
# To find rank of the matrix
import numpy as np
mx = np.array([[1,1,1],[0,1,2],[1,5,3]])
R = np.linalg.matrix_rank(mx)
print(mx)
print("The Rank of the Matrix is :",R)

[[1 1 1]
 [0 1 2]
 [1 5 3]]
The Rank of the Matrix is : 3


In [9]:
# TO find solutions of homogeneous linear equations
from sympy import *
x,y,z =symbols('x,y,z')
n = int(input("Enter the number of unknowns: "))
a11,a12,a13 = 1,3,-2
a21,a22,a23 = 2,-1,4
a31,a32,a33 = 1,-11,14
A = Matrix(([a11,a12,a13],[a21,a22,a23],[a31,a32,a33]))
ra = A.rank()
print("The rank of matrix A is: ",ra)
if(ra == n):
    print("The system has only trivial solution")
else:
    print("The system has non-trivial solution ")
    print(linsolve([a11*x+a22*y+a13*z,a21*x+a22*y+a23*z+a31*x+a32*y+a33*z],[x,y,z]))

The rank of matrix A is:  2
The system has non-trivial solution 
{(14*z/3, 8*z/3, z)}


In [17]:
#To find eigen values and eigen vectors
import numpy as np 
a = np.array([[-1,3],[-2,4]])
print(a)
from numpy.linalg import eig 
values,vectors = eig(a)
print("The eigen values of matrix a is",values)
print("The eigen vectors of matrix a is",vectors)

[[-1  3]
 [-2  4]]
The eigen values of matrix a is [1. 2.]
The eigen vectors of matrix a is [[-0.83205029 -0.70710678]
 [-0.5547002  -0.70710678]]


In [18]:
#To find eigen values and eigen vectorsimport numpy as np
a = np.array([[1,1,3],[1,5,1],[3,1,1]])
print(a)
from numpy.linalg import eig
values,vectors = eig(a)
print("The eigen values of the given matrix is",values)
print("The eigen vectors of the given matrix is", vectors)

[[1 1 3]
 [1 5 1]
 [3 1 1]]
The eigen values of the given matrix is [-2.  3.  6.]
The eigen vectors of the given matrix is [[ 7.07106781e-01 -5.77350269e-01 -4.08248290e-01]
 [-2.50450702e-17  5.77350269e-01 -8.16496581e-01]
 [-7.07106781e-01 -5.77350269e-01 -4.08248290e-01]]


In [20]:
#Diagonalize the matrix 
from sympy import *
M = Matrix([[8,-6,2],[-6,7,-4],[2,-4,3]])
print("Matrix : {}".format(M))
P,D = M.diagonalize()
print("Diagonal of matrix is: {}".format(D))

Matrix : Matrix([[8, -6, 2], [-6, 7, -4], [2, -4, 3]])
Diagonal of matrix is: Matrix([[0, 0, 0], [0, 3, 0], [0, 0, 15]])


In [24]:
#Finding the Partial Derivatives 
#Find the first order partial derivatives of f(x, y, z) = 4xy+xsinz+x3+yz8
from sympy import *
x,y,z = symbols('x,y,z',real=True)
f = 4*x*y+x*sin(z)+x**3+y*z**8
Fx = diff(f,x)
Fy = diff(f,y)
Fz = diff(f,z)
print("The first order derivative of F w.r.t x = ",Fx)
print("The first order derivative of F w.r.t y = ",Fy)
print("The first order derivative of F w.r.t z = ",Fz)


The first order derivative of F w.r.t x =  3*x**2 + 4*y + sin(z)
The first order derivative of F w.r.t y =  4*x + z**8
The first order derivative of F w.r.t z =  x*cos(z) + 8*y*z**7
