In [4]:
# To find rank of the matrix
import numpy as np
mx = np.array([[1,1,1],[0,1,2],[1,5,3]])
R = np.linalg.matrix_rank(mx)
print(mx)
print("The Rank of the Matrix is :",R)

[[1 1 1]
 [0 1 2]
 [1 5 3]]
The Rank of the Matrix is : 3


In [9]:
# TO find solutions of homogeneous linear equations
from sympy import *
x,y,z =symbols('x,y,z')
n = int(input("Enter the number of unknowns: "))
a11,a12,a13 = 1,3,-2
a21,a22,a23 = 2,-1,4
a31,a32,a33 = 1,-11,14
A = Matrix(([a11,a12,a13],[a21,a22,a23],[a31,a32,a33]))
ra = A.rank()
print("The rank of matrix A is: ",ra)
if(ra == n):
    print("The system has only trivial solution")
else:
    print("The system has non-trivial solution ")
    print(linsolve([a11*x+a22*y+a13*z,a21*x+a22*y+a23*z+a31*x+a32*y+a33*z],[x,y,z]))

The rank of matrix A is:  2
The system has non-trivial solution 
{(14*z/3, 8*z/3, z)}


In [17]:
#To find eigen values and eigen vectors
import numpy as np 
a = np.array([[-1,3],[-2,4]])
print(a)
from numpy.linalg import eig 
values,vectors = eig(a)
print("The eigen values of matrix a is",values)
print("The eigen vectors of matrix a is",vectors)

[[-1  3]
 [-2  4]]
The eigen values of matrix a is [1. 2.]
The eigen vectors of matrix a is [[-0.83205029 -0.70710678]
 [-0.5547002  -0.70710678]]


In [18]:
#To find eigen values and eigen vectorsimport numpy as np
a = np.array([[1,1,3],[1,5,1],[3,1,1]])
print(a)
from numpy.linalg import eig
values,vectors = eig(a)
print("The eigen values of the given matrix is",values)
print("The eigen vectors of the given matrix is", vectors)

[[1 1 3]
 [1 5 1]
 [3 1 1]]
The eigen values of the given matrix is [-2.  3.  6.]
The eigen vectors of the given matrix is [[ 7.07106781e-01 -5.77350269e-01 -4.08248290e-01]
 [-2.50450702e-17  5.77350269e-01 -8.16496581e-01]
 [-7.07106781e-01 -5.77350269e-01 -4.08248290e-01]]


In [20]:
#Diagonalize the matrix 
from sympy import *
M = Matrix([[8,-6,2],[-6,7,-4],[2,-4,3]])
print("Matrix : {}".format(M))
P,D = M.diagonalize()
print("Diagonal of matrix is: {}".format(D))

Matrix : Matrix([[8, -6, 2], [-6, 7, -4], [2, -4, 3]])
Diagonal of matrix is: Matrix([[0, 0, 0], [0, 3, 0], [0, 0, 15]])


In [24]:
#Finding the Partial Derivatives 
#Find the first order partial derivatives of f(x, y, z) = 4xy+xsinz+x3+yz8
from sympy import *
x,y,z = symbols('x,y,z',real=True)
f = 4*x*y+x*sin(z)+x**3+y*z**8
Fx = diff(f,x)
Fy = diff(f,y)
Fz = diff(f,z)
print("The first order derivative of F w.r.t x = ",Fx)
print("The first order derivative of F w.r.t y = ",Fy)
print("The first order derivative of F w.r.t z = ",Fz)


The first order derivative of F w.r.t x =  3*x**2 + 4*y + sin(z)
The first order derivative of F w.r.t y =  4*x + z**8
The first order derivative of F w.r.t z =  x*cos(z) + 8*y*z**7


In [1]:
#Partial Derivatives by Jacobian Method
#Find the Jacobian when u = x(1 − y) and v = xy.
from sympy import *
x,y = symbols('x,y')
u = x*(1-y)
v = x*y
A = Matrix([u,v])
jacA = A.jacobian([x,y])
print(jacA)
Jacobian = simplify(det(jacA))
print("Jacobian(A) = ",Jacobian)


Matrix([[1 - y, -x], [y, x]])
Jacobian(A) =  x


In [15]:
#Finding the angle between the radius vector and tangent
#Find the angle between radius vector and the tangent for the curve r = a (1 + cos t) at t = π/6.
from sympy import *
a,t=symbols('a,t')
R=a*(1+cos(t))
dRdt=diff(R,t)
R=R.subs(t,pi/6)
dRdt=dRdt.subs(t,pi/6)
PHI=atan(R/dRdt)
print('The angle between the radius vector and the tangent =',PHI)
if PHI<0:
   PHI=PHI+pi
print('The angle between the radius vector and the tangent =',PHI)


The angle between the radius vector and the tangent = -5*pi/12
The angle between the radius vector and the tangent = 7*pi/12


In [5]:
#8. Finding the radius of curvature in cartesian, parametric, polar and pedal forms (Common for all)
# a.Find the radius of curvature for the curve xy = c2 in cartesian form.
from sympy import *
x,y,c=symbols('x,y,c')
y=c**2/x
y1=diff(y,x)
y2=diff(y,x,2)
roh=(1+y1**2)**(3/2)/y2
print('Radius of curvature is',roh)


Radius of curvature is x**3*(c**4/x**4 + 1)**1.5/(2*c**2)


In [3]:
#b. Find the radius of curvature for the curve x = a (t + sin t), y = a (1 − cos t) at t = 0 in parametric form.

from sympy import *
x,y,a,t=symbols('x,y,a,t')
x=a*(t+sin(t))
y=a*(1-cos(t))
x1=diff(x,t)
x2=diff(x1,t)
y1=diff(y,t)
y2=diff(y1,t)
roh=simplify((x1**2+y1**2)**(3/2)/(x1*y2-y1*x2))
roh=simplify(roh.subs(t,0))
print('Radius of curvature is',roh)

Radius of curvature is 4.0*(a**2)**0.5


In [2]:
#c.Find the radius of curvature for the curve r = a (1 + cos t) at t = 0 in polar form
from sympy import *
x,y,a,t=symbols('x,y,a,t')
r=a*(1+cos(t))
r1=diff(r,t)
r2=diff(r1,t)
roh=simplify((r**2+r1**2)**(3/2)/(r**2+2*r1**2-r*r2))
roh=simplify(roh.subs(t,0))
print('Radius of curvature is',roh)


Radius of curvature is 1.33333333333333*(a**2)**0.5


In [1]:
# d.Find the radius of curvature for the curve r3 = 2ap2 in pedal form.

from sympy import *
p,a=symbols('p,a')
r=(2*a*p**2)**(1/3)
r1=diff(r,p)
roh=simplify(r*r1)
print('Radius of curvature is',roh)


Radius of curvature is 1.0582673679788*(a*p**2)**0.666666666666667/p


In [9]:
#9. Finding the Permutations
#a. Find all permutations of 1, 2, 3 of length 2.
from itertools import permutations
count = 0
perm = permutations([1,2,3],2)
for i in list(perm):
    count+=1
    print(i)
print("Total no of permutations =",count)

(1, 2)
(1, 3)
(2, 1)
(2, 3)
(3, 1)
(3, 2)
Total no of permutations = 6


In [10]:
#10. Finding the Combinations
#a. Find all combinations of 1, 2, 3 of length 2.
from itertools import combinations
count = 0
comb = combinations([1,2,3],2)
for i in list(comb):
    count+=1
    print(i)
print("Total no of combinations =",count)

(1, 2)
(1, 3)
(2, 3)
Total no of combinations = 3
